### ISSUE TITLE
Tag v0.6.0 to demarcate Swift 1.2 support

### ISSUE THREAD

**Issue by modocache** [LlamaKit/LlamaKit#29]
Following 7569c59f49b0d4033a06409745a44f8566189e98, LlamaKit no longer builds on Swift 1.1 or prior. How about cutting a tag for Swift 1.2-compatible LlamaKit?

**Comment by MrAlek** [comment]
Would very much appreciate a tag for Swift 1.2 support.

**Comment by rnapier** [comment]
Tagged v0.6.0.

**Comment by MrAlek** [comment]
Thanks!
