### ISSUE TITLE
Push new podspec versions to CocoaPods

### ISSUE THREAD

**Issue by modocache** [LlamaKit/LlamaKit#33]
@ashfurrow is probably the person to bug about this, but the latest version of LlamaKit that's on CoocaPods is v0.1.1. Any chance of gettting the latest versions up on there, specifically v0.5.0 and #32's v0.6.0?

**Comment by ashfurrow** [comment]
Yup can do. I'll mark v0.6.0 as requiring iOS 8.3+ to avoid problems with non-beta versions of Xcode (we can change this later if we have to).

**Comment by ashfurrow** [comment]
M'kay. 0.5.0 is up. Working on 0.6.0 now.

**Comment by ashfurrow** [comment]
These are both on Trunk. I've opened #34 to update the podspec on the repo.
