### ISSUE TITLE
LlamaKit doesn't link to Foundation

### ISSUE THREAD

**Issue by barksten** [LlamaKit/LlamaKit#35]
LlamaKit (0.6.0) doesn't link to Foundation. This causes a build failure in Cartage with Xcode6.3b2.

**Comment by barksten** [comment]
I've made a [PR](https://github.com/LlamaKit/LlamaKit/pull/36) for this issue

**Comment by modocache** [comment]
This issue can be closed, @rnapier! :wave:

**Comment by barksten** [comment]
Thanks for reminding!
